//
//  FavouriteConfig.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteConfig: BaseConfig{
    func createModule(view: FavouriteViewController) {
        
        let interactor: FavouriteInteractor = FavouriteInteractor()
        let router: FavouriteRouter = FavouriteRouter()
        
        let presenter: FavouritePresenter = FavouritePresenter(view: view, interactor: interactor, router: router)
        
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
