//
//  FavouriteViewController.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteViewController: BaseViewController, FavouriteViewProtocol {
    
    @IBOutlet weak var favCollection: UICollectionView!
    var presenter: FavouritePresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        FavouriteConfig().createModule(view: self)
        self.setNavigation()
        navigationController?.navigationBar.prefersLargeTitles = true
        self.title = "My Favourite"
        navigationController?.navigationBar.largeTitleTextAttributes = [.foregroundColor: UIColor.red]
        
    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.presenter?.loadFavouriteImages()
    }
    
    
}
