//
//  FavouriteInteractor.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteInteractor: BaseInteractor<AppTarget>,FavouriteInteractorInputProtocol {
    
    weak var presenter: FavouriteInteractorOutputProtocol?
    func loadAllObjects() {
        let allObjects = CacheHandler.shared.loadAllCachedData()
        presenter?.didLoadAllObjects(movies:  constructMovies(detailObjs: allObjects))
    }
    
    private func constructMovies(detailObjs:[MovieDetailsResponse]) -> [Movie] {
        var movies = [Movie]()
        for item in detailObjs {
            let movie = Movie(obj: item)
            movies.append(movie)
        }
        return movies
    }
    

}
