//
//  FavouritePresenter.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouritePresenter: BasePresenter,FavouritePresenterProtocol {
    
    @IBOutlet weak var favCollection: UICollectionView!
    weak internal var view: FavouriteViewProtocol?
    var interactor: FavouriteInteractorInputProtocol?
    private let router: FavouriteRouterProtocol
    private var dataSource:MovieCellDataSource?
    
    init(view: FavouriteViewProtocol, interactor: FavouriteInteractorInputProtocol?, router: FavouriteRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    func loadFavouriteImages() {
        self.interactor?.loadAllObjects()
    }
    
}

extension FavouritePresenter: FavouriteInteractorOutputProtocol {
    func didLoadAllObjects(movies: [Movie]?) {
        if let movies = movies {
            self.baseView?.hideLoadingIndicator()
            guard let collection = self.view?.favCollection else {
                return
            }
            dataSource = MovieCellDataSource(collection: collection, delegate: self, movies: movies)
        }
    }
    
    
}

extension FavouritePresenter:MovieCellDelegate{
    func didSelect(movie: Movie) {
        //router.showDetails(movie: movie)
    }
    
}

