//
//  FavouriteProtocols.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol FavouriteViewProtocol: class {
    var presenter: FavouritePresenterProtocol?  { get set }
    var favCollection: UICollectionView! { get set }
}
//MARK: Presenter -
protocol FavouritePresenterProtocol: class {
    var view: FavouriteViewProtocol?  { get set }
    
    func loadFavouriteImages()
}

//MARK: Interactor -
protocol FavouriteInteractorOutputProtocol: class {
    func didLoadAllObjects (movies:[Movie]?)
  
}
protocol FavouriteInteractorInputProtocol: class {

  var presenter: FavouriteInteractorOutputProtocol?  { get set }
    func loadAllObjects()
}

//MARK: Router -
protocol FavouriteRouterProtocol: class {
    var view: UIViewController! { get set }
    
}
