//
//  FavouriteRouter.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FavouriteRouter: FavouriteRouterProtocol {
    
     var view: UIViewController!
    
  
}
