//
//  NowPlayingViewController.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NowPlayingViewController: BaseViewController, NowPlayingViewProtocol {
    
    var presenter: NowPlayingPresenterProtocol?
    
    @IBOutlet weak var labelInternet: UILabel!
    @IBOutlet weak var nowPlayingCollection: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        NowPlayingConfig().createModule(view: self)
        
        self.setNavigation()
        navigationController?.navigationBar.prefersLargeTitles = true
        self.title = "Now Playing"
        navigationController?.navigationBar.largeTitleTextAttributes = [.foregroundColor: UIColor.red]
        listenToNetwork()
        
    }
    func listenToNetwork()  {
        Reachability().checkForInternet(action: { (value) in
            DispatchQueue.main.async {
                if value {
                    self.labelInternet.isHidden = true
                    self.nowPlayingCollection.isHidden = false
                    self.presenter?.loadNowPlayingMovies()
                } else {
                    self.labelInternet.isHidden = false
                    self.nowPlayingCollection.isHidden = true
                }
            }
        })
    }
    
}
