//
//  NowPlayingProtocols.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol NowPlayingViewProtocol: class {
    var presenter: NowPlayingPresenterProtocol?  { get set }
    var nowPlayingCollection: UICollectionView!  { get set }
}
//MARK: Presenter -
protocol NowPlayingPresenterProtocol: class {
    var view: NowPlayingViewProtocol?  { get set }
    func loadNowPlayingMovies()  
}

//MARK: Interactor -
protocol NowPlayingInteractorOutputProtocol: class {
    func didLoadNowPlayingMovies(movies:[Movie])
    func didRequestSession()
}
protocol NowPlayingInteractorInputProtocol: class {

  var presenter: NowPlayingInteractorOutputProtocol?  { get set }
    func fetchNowPlayingMovies()
    func requestSessionId()
}

//MARK: Router -
protocol NowPlayingRouterProtocol: class {
    var view: UIViewController! { get set }
    func showDetails(movie:Movie)
}
