//
//  NowPlayingPresenter.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NowPlayingPresenter: BasePresenter,NowPlayingPresenterProtocol {
    
    weak internal var view: NowPlayingViewProtocol?
    var interactor: NowPlayingInteractorInputProtocol?
    
    private let router: NowPlayingRouterProtocol
    
    private var dataSource:MovieCellDataSource?
    
    init(view: NowPlayingViewProtocol, interactor: NowPlayingInteractorInputProtocol?, router: NowPlayingRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    func loadNowPlayingMovies() {
        self.baseView?.showLoadingIndicator()
        self.interactor?.fetchNowPlayingMovies()
    }
    
}

extension NowPlayingPresenter: NowPlayingInteractorOutputProtocol {
    func didRequestSession() {
        self.baseView?.hideLoadingIndicator()
    }
    
    func didLoadNowPlayingMovies(movies: [Movie]) {
        self.baseView?.hideLoadingIndicator()
        guard let collection = self.view?.nowPlayingCollection else {
            return
        }
        dataSource = MovieCellDataSource(collection: collection, delegate: self, movies: movies)
        self.baseView?.showLoadingIndicator()
        self.interactor?.requestSessionId()
    }
    
    
}
extension NowPlayingPresenter:MovieCellDelegate{
    func didSelect(movie: Movie) {
        router.showDetails(movie: movie)
    }
    
}
