//
//  NowPlayingConfig.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NowPlayingConfig: BaseConfig{
    func createModule(view: NowPlayingViewController) {
        
        let interactor: NowPlayingInteractor = NowPlayingInteractor()
        let router: NowPlayingRouter = NowPlayingRouter()
        
        let presenter: NowPlayingPresenter = NowPlayingPresenter(view: view, interactor: interactor, router: router)
        
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
