//
//  DetailRouter.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailRouter: DetailRouterProtocol {
    
     var view: UIViewController!
    
    func showDetails(movie: Movie) {
        let vc:DetailViewController = UIViewController.instanceXib()
        DetailConfig().createModule(view: vc, movie: movie)
        view.show(vc, sender: view)
    }
    
  
}
