//
//  DetailProtocols.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
import Cosmos
//MARK: View -
protocol DetailViewProtocol: class {
    var presenter: DetailPresenterProtocol?  { get set }
    
    var similarCollection: UICollectionView! { get set }
    var labelOverview: UILabel! { get set }
    var labelRate: UILabel! { get set }
    var labelGenres: UILabel! { get set }
    var labelRelease: UILabel! { get set }
    var labelTitle: UILabel! { get set }
    var posterImageView: UIImageView! { get set }
    var ratingView: CosmosView! { get set }
    func didRateMovie()
}
//MARK: Presenter -
protocol DetailPresenterProtocol: class {
    var view: DetailViewProtocol?  { get set }
    
    func isFavourite() -> Bool
    func loadMovieDetails()
    func rateMovie(rating:Double)
    func toggleFavouirte()
}

//MARK: Interactor -
protocol DetailInteractorOutputProtocol: class {
    func didSimilarMovies(movies:[Movie])
    func didFetchMovieDetails(movie:MovieDetailsResponse)
    func didRateMovie ()
}
protocol DetailInteractorInputProtocol: class {

  var presenter: DetailInteractorOutputProtocol?  { get set }
    func loadSimilarMovies(to id:Int)
    func loadMovieDetails()
    func rateMovie(rate:Double)
    func toggleFavourte(movie:Movie)
    func isFavourite() -> Bool
    
}

//MARK: Router -
protocol DetailRouterProtocol: class {
    var view: UIViewController! { get set }
    func showDetails(movie: Movie) 
    
}
