//
//  DetailViewController.swift
//  TheMovieDb
//
//  Created Mena Gamal on 8/22/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Cosmos
class DetailViewController: BaseViewController, DetailViewProtocol {
    
    var presenter: DetailPresenterProtocol?
    
    @IBOutlet weak var similarCollection: UICollectionView!
    
    @IBOutlet weak var ratingView: CosmosView!
    @IBOutlet weak var labelOverview: UILabel!
    @IBOutlet weak var labelRate: UILabel!
    @IBOutlet weak var labelGenres: UILabel!
    @IBOutlet weak var labelRelease: UILabel!
    @IBOutlet weak var labelTitle: UILabel!
    @IBOutlet weak var posterImageView: UIImageView!
    
    @IBOutlet weak var btnFav: UIButton!
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setNavigation()
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationController?.navigationBar.largeTitleTextAttributes = [.foregroundColor: UIColor.red]
        self.presenter?.loadMovieDetails()
        ratingView.didFinishTouchingCosmos = { rating in
            self.presenter?.rateMovie(rating: rating)
        }
        
    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        guard  let presenter = presenter else {
            return
        }
        DispatchQueue.main.async {
            
            if presenter.isFavourite() {
                self.btnFav.setTitle("Remove Form Favourite", for: .normal)
            } else {
                self.btnFav.setTitle("Add To Favourite", for: .normal)
            }
           
        }
        
    }
    
    @IBAction func toggleFav(_ sender: Any) {
        self.presenter?.toggleFavouirte()
        guard  let presenter = presenter else {
            return
        }
        if presenter.isFavourite() {
            self.btnFav.setTitle("Remove Form Favourite", for: .normal)
        } else {
            self.btnFav.setTitle("Add To Favourite", for: .normal)
        }
        
    }
    
    func didRateMovie() {
        //
    }
    
}
